development:
  enable_star: true
  min_infix_len: 2

test: &TEST
  port: 3313
  enable_star: true
  min_infix_len: 2

production:
  enable_star: true
  min_infix_len: 2
  bin_path: '/usr/local/bin'

cucumber:
  <<: *TEST
